# Generated by Django 2.0 on 2018-08-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResortInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResortInfo', models.CharField(max_length=200)),
                ('Continent', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('URL', models.CharField(max_length=200)),
                ('Currency', models.CharField(max_length=200)),
                ('Altitude', models.FloatField()),
                ('Easy', models.FloatField()),
                ('Intermediate', models.FloatField()),
                ('Difficult', models.FloatField()),
                ('Funicular', models.FloatField()),
                ('Gondola', models.FloatField()),
                ('Chairlift', models.FloatField()),
                ('Buttons', models.FloatField()),
                ('MovingCarpet', models.FloatField()),
                ('Adult', models.FloatField()),
                ('Youth', models.FloatField()),
                ('Child', models.FloatField()),
                ('ResortSize', models.FloatField()),
                ('Variety', models.FloatField()),
                ('Lifts', models.FloatField()),
                ('Reliability', models.FloatField()),
                ('SlopePreparation', models.FloatField()),
                ('Access', models.FloatField()),
                ('Orientation', models.FloatField()),
                ('Cleanliness', models.FloatField()),
                ('EnvironmentallyFriendly', models.FloatField()),
                ('Friendliness', models.FloatField()),
                ('RestaurantsAndFood', models.FloatField()),
                ('ApresSki', models.FloatField()),
                ('SkiInSkiOutAccomodation', models.FloatField()),
                ('FamiliesAndChildren', models.FloatField()),
                ('Beginners', models.FloatField()),
                ('Advanced', models.FloatField()),
                ('SnowParks', models.FloatField()),
                ('CrossCountry', models.FloatField()),
                ('AerialTramway', models.FloatField()),
                ('RopeTow', models.FloatField()),
                ('PeopleMover', models.FloatField()),
                ('GondolaAndLift', models.FloatField()),
                ('CogRailway', models.FloatField()),
                ('Heliskiing', models.FloatField()),
                ('CatSkiing', models.FloatField()),
            ],
        ),
    ]
