# Generated by Django 2.0 on 2018-08-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resortinfo',
            old_name='ResortInfo',
            new_name='ResortName',
        ),
    ]
