# Generated by Django 2.0 on 2018-08-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20180805_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resortinfo',
            name='Access',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Adult',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Advanced',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='AerialTramway',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='ApresSki',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Beginners',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Buttons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='CatSkiing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Chairlift',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Child',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Cleanliness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='CogRailway',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='CrossCountry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Difficult',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Easy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='EnvironmentallyFriendly',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='FamiliesAndChildren',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Friendliness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Funicular',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Gondola',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='GondolaAndLift',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Heliskiing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Intermediate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Lifts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='MovingCarpet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Orientation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='PeopleMover',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Reliability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='ResortSize',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='RestaurantsAndFood',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='RopeTow',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='SkiInSkiOutAccomodation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='SlopePreparation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='SnowParks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Variety',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='Youth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
