# Generated by Django 2.0 on 2018-08-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20180805_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resortinfo',
            name='State',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resortinfo',
            name='URL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
